# Generated by Django 5.1.1 on 2025-08-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinscripcion',
            fields=[
                ('id_reinscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_escolar', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('documento_pdf', models.FileField(upload_to='documentos/reinscripciones/')),
                ('fecha_reinscripcion', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
    ]
