# Generated by Django 5.1.1 on 2025-08-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinscripcion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
