# Generated by Django 5.1.1 on 2025-08-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
