# Generated by Django 5.1.1 on 2025-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20)),
                ('documento_pdf', models.FileField(upload_to='documentos/tutores/')),
            ],
        ),
    ]
