# Generated by Django 5.1.1 on 2025-08-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_remove_tutor_documento_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
