# Generated by Django 5.1.1 on 2025-10-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
