# Generated by Django 5.1.1 on 2025-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotMensaje',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=100, unique=True)),
                ('respuesta', models.TextField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
