# Generated by Django 5.1.1 on 2025-10-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupo', '0003_remove_cupo_cupos_tecnico'),
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('cupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_tecnicos', to='cupo.cupo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_asignados', to='tecnico.tecnico')),
            ],
            options={
                'verbose_name': 'Cupo por Técnico',
                'verbose_name_plural': 'Cupos por Técnico',
                'unique_together': {('cupo', 'tecnico')},
            },
        ),
    ]
