# Generated by Django 5.1.1 on 2025-10-17 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupo', '0003_remove_cupo_cupos_tecnico'),
        ('cupotecnico', '0001_initial'),
        ('grado', '0001_initial'),
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cupotecnico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cupotecnico',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupos_por_tecnico', to='grado.grado'),
        ),
        migrations.AlterUniqueTogether(
            name='cupotecnico',
            unique_together={('cupo', 'tecnico', 'grado')},
        ),
    ]
