# Generated by Django 5.1.1 on 2025-08-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='seccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
