# Generated by Django 5.1.1 on 2025-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_inscripcion_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='documento_pdf',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='acta_nacimiento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/inscripciones/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cedula_tutor',
            field=models.FileField(blank=True, null=True, upload_to='documentos/inscripciones/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='certificado_medico',
            field=models.FileField(blank=True, null=True, upload_to='documentos/inscripciones/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='foto_estudiante',
            field=models.FileField(blank=True, null=True, upload_to='documentos/inscripciones/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='record_notas',
            field=models.FileField(blank=True, null=True, upload_to='documentos/inscripciones/'),
        ),
    ]
