# Generated by Django 5.1.1 on 2025-08-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_remove_inscripcion_documento_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
