# Generated by Django 5.1.1 on 2025-08-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_inscripcion_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='telefono',
        ),
    ]
