# Generated by Django 5.1.1 on 2025-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('contenido', models.TextField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
