# Generated by Django 5.1.1 on 2025-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Inscripcion', 'Inscripción'), ('Reinscripcion', 'Reinscripción')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('cupos_1ro', models.PositiveIntegerField(default=0)),
                ('cupos_2do', models.PositiveIntegerField(default=0)),
                ('cupos_3ro', models.PositiveIntegerField(default=0)),
                ('cupos_tecnico', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
