# Generated by Django 5.1.1 on 2025-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupo',
            old_name='cupos_1ro',
            new_name='cupos_1ro_A',
        ),
        migrations.RenameField(
            model_name='cupo',
            old_name='cupos_2do',
            new_name='cupos_1ro_B',
        ),
        migrations.RenameField(
            model_name='cupo',
            old_name='cupos_3ro',
            new_name='cupos_1ro_C',
        ),
        migrations.AddField(
            model_name='cupo',
            name='cupos_2do_A',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupo',
            name='cupos_2do_B',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupo',
            name='cupos_2do_C',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupo',
            name='cupos_3ro_A',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupo',
            name='cupos_3ro_B',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupo',
            name='cupos_3ro_C',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
