# Generated by Django 5.1.1 on 2025-10-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupo', '0002_rename_cupos_1ro_cupo_cupos_1ro_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupo',
            name='cupos_tecnico',
        ),
    ]
